### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by isabelle1208** [ph4r05/NATSimTools#1]
Hi!
When I run simulation.py like this,
python simulation.py
there is no log file to output.
I don't know how to run server.py and client.py.
Can you reply me soon? Thanks.

**Comment by ph4r05** [comment]
I am sorry, this project is unmaintained for more than 5 years. What do you need in particular?

**Comment by isabelle1208** [comment]
I just want to use simulation.py to simulate symmetric nat.

发自我的 iPhone

> 在 2019年3月13日，18:19，Dušan Klinec <notifications@github.com> 写道：
> 
> What do you need in particular?
>

**Comment by ph4r05** [comment]
I am sorry, but I don't know how to operate it after such a long time and I am quite busy to dive into it.

**Comment by isabelle1208** [comment]
Ok，thank you anyway

发自我的 iPhone
